# GitOps test manifest; update, push and wait for whatever GitOps tool used does its duty
---
apiVersion: v1
kind: Namespace
metadata:
  name: prod
  labels:
    env: production
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kcheck
  namespace: prod
  labels:
    type: front-end
spec:
  selector:
    matchLabels:
      app: kcheck
  replicas: 2
  template:
    metadata:
      labels:
        app: kcheck
    spec:
      containers:
      - name: kcheck
        image: "ghcr.io/wolcn/kcheck:1.0.2" # OCI image
        imagePullPolicy: IfNotPresent
        # Some environment values; if not set default values will be used
        env:
        - name: COLOUR # HTML colour name for background colour
          # Examples "Cornsilk","Bisque","Wheat","NavajoWhite","Moccasin","LightSteelBlue","DarkSeaGreen","SeaGreen","Khaki","Silver"
          value: "LightSteelBlue"
        - name: CONTENT # Content string; useful when checking if deployment has been updated
          value: "This is the production environment"
---
apiVersion: v1
kind: Service
metadata:
  name: kcheck-service
  namespace: prod
  labels:
    app: kcheck
    type: service
spec:
  type: LoadBalancer
  selector:
    app: kcheck
  ports:
    # The external LB port is 80
  - port: 80
    targetPort: 8080
    protocol: TCP
